threshold: 40
min_investment_balance: 100
main:
  account: "125647287449802290"
  memo: bofa
  low: 6000
  high: 10000
preferred:
  gold: IAUM/IAU
  bond: FNBGX/VGLT
  cash: FUMBX/VGSH
  smallcap: FCPVX/AVUV
  stock: FZROX/VTI/ITOT
  reit: VNQ
  reit-intl: VNQI
  smallcap-intl: AVDV
  other: "???"
vesting:
- "162522988589078420"
- "162522988632070037"
